// <auto-generated />
using System;
using Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240416112249_4")]
    partial class _4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Postalcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebApi.Entities.CourseEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseGoal1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseGoal2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseGoal3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseGoal4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseGoal5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseIncludes1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseIncludes2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseIncludes3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseIncludes4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseIncludes5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<bool>("IsBestseller")
                        .HasColumnType("bit");

                    b.Property<decimal>("LikesInNumbers")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LikesInProcent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProgramDetailDescription1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramDetailDescription2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramDetailDescription3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramDetailDescription4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramDetailDescription5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramDetailDescription6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramDetailTitle1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramDetailTitle2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramDetailTitle3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramDetailTitle4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramDetailTitle5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramDetailTitle6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = "421a59de-432c-4149-90d8-c55e30f6ccf0",
                            Author = "Robert Fox",
                            AuthorDescription = "Robert Fox is a seasoned full-stack web developer with over 10 years of experience in the industry. He has a passion for teaching and has helped thousands of students worldwide master web development concepts. With expertise in HTML, CSS, JavaScript, and various backend technologies, Robert brings a wealth of knowledge to his courses. He believes in hands-on learning and practical examples, ensuring that his students gain real-world skills that they can apply immediately. Outside of coding, Robert enjoys hiking, playing the guitar, and experimenting with new tech gadgets.\r\n",
                            CourseDescription = "Welcome to the Fullstack Web Developer Course from Scratch! In this comprehensive 220-hour course, you'll master HTML, CSS, JavaScript, and backend technologies. Learn to build responsive websites, dynamic web apps, and deploy them to production. Gain essential soft skills for a successful career. Enroll now and kickstart your journey to becoming a professional full-stack developer!",
                            CourseGoal1 = "Master core full-stack web development principles.",
                            CourseGoal2 = "Design responsive web interfaces with CSS.",
                            CourseGoal3 = "Implement dynamic web applications using JavaScript.",
                            CourseGoal4 = "Learn server-side programming and database management.",
                            CourseGoal5 = "Develop user-friendly and interactive web apps.",
                            CourseImagePath = "fullstack_web_dev.svg",
                            CourseIncludes1 = "148 hours on-demand video",
                            CourseIncludes2 = "18 articles",
                            CourseIncludes3 = "25 downloadable resources",
                            CourseIncludes4 = "Full lifetime access",
                            CourseIncludes5 = "Certificate of completion",
                            DiscountPrice = 0m,
                            Hours = 220,
                            IsBestseller = true,
                            LikesInNumbers = 4200m,
                            LikesInProcent = 0.94m,
                            OriginalPrice = 12.50m,
                            ProgramDetailDescription1 = "Begin your journey into web development with this introductory section. Explore the basic concepts and tools needed to start building web applications. Understand the structure of web pages, the role of HTML, and the basics of setting up your development environment. By the end of this section, you'll have a solid foundation to build upon as you progress through the course.",
                            ProgramDetailDescription2 = "Take your HTML skills to the next level with this advanced HTML course. Learn advanced techniques for structuring content, creating semantic markup, and optimizing code for performance. Dive deep into topics like responsive design, multimedia integration, and accessibility to create modern and interactive web experiences.",
                            ProgramDetailDescription3 = "Master the fundamentals of CSS and CSS3 to style and design your web pages. Learn about selectors, properties, and the box model to control layout and appearance. Explore basic CSS techniques for styling text, backgrounds, and borders, and understand how to use CSS frameworks for rapid development. By the end of this section, you'll have a solid understanding of CSS basics and be ready to enhance your web pages with style.",
                            ProgramDetailDescription4 = "Get started with JavaScript and unlock the power of dynamic web development. Learn the basics of JavaScript syntax, variables, and data types, and understand how to use control structures and functions to create interactive web applications. Dive into DOM manipulation to dynamically update web content and handle user interactions. By the end of this section, you'll have a strong foundation in JavaScript programming and be ready to tackle more advanced concepts.",
                            ProgramDetailDescription5 = "Discover the world of APIs and their role in modern web development. Learn how to consume APIs to access external data and services and integrate them into your web applications. Understand common API architectures, such as RESTful APIs, and learn best practices for making API requests and handling responses. By the end of this section, you'll have a solid understanding of APIs and be able to leverage them to enhance your web projects.",
                            ProgramDetailDescription6 = "Take your web development skills to the next level with C# and .NET. Learn the fundamentals of C# programming, including data types, control structures, and object-oriented programming concepts. Explore the .NET framework and understand how to use it to build scalable and secure web applications. Dive into advanced topics like asynchronous programming, LINQ, and MVC architecture to develop robust and maintainable web solutions. By the end of this section, you'll have the skills and knowledge to build professional-grade web applications with C# and .NET.",
                            ProgramDetailTitle1 = "Introduction. Getting started",
                            ProgramDetailTitle2 = "The ultimate HTML developer: advanced HTML",
                            ProgramDetailTitle3 = "CSS & CSS3: basic",
                            ProgramDetailTitle4 = "JavaScript basics for beginners",
                            ProgramDetailTitle5 = "Understanding APIs",
                            ProgramDetailTitle6 = "C# and .NET from beginner to advanced",
                            Title = "Fullstack Web Developer Course from Scratch",
                            TitleDescription = "Master full-stack web development. Learn HTML, CSS, JavaScript, Node.js, and build real projects."
                        },
                        new
                        {
                            Id = "c943a5af-2a94-40b4-8f6b-644328d843ee",
                            Author = "Jenny Wilson",
                            AuthorDescription = "Jenny Wilson is a proficient web developer specializing in front-end technologies. With years of experience in HTML, CSS, and JavaScript, she has crafted numerous interactive and visually appealing web applications. Jenny has a knack for simplifying complex concepts and enjoys sharing her knowledge with aspiring developers. In her spare time, she contributes to open-source projects and enjoys photography.",
                            CourseDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et urna et dui lobortis vestibulum. Nam nec orci at ex mattis bibendum in a velit. Duis id ante quis nisl blandit gravida ac nec lorem. Proin vitae lacus vitae lorem tincidunt viverra. Integer commodo elit in enim interdum tempor. Sed vitae ligula vitae orci ullamcorper suscipit in sit amet nunc. In hac habitasse platea dictumst.",
                            CourseGoal1 = "Master the fundamentals of HTML including tags, attributes, and semantic markup.",
                            CourseGoal2 = "Gain proficiency in styling web pages using CSS and understand advanced concepts like flexbox and grid layout.",
                            CourseGoal3 = "Learn JavaScript from scratch, including variables, functions, control structures, and DOM manipulation.",
                            CourseGoal4 = "Understand how to create responsive and interactive web applications.",
                            CourseGoal5 = "Get insights into best practices and industry-standard workflows for web development.",
                            CourseImagePath = "html_css_js.svg",
                            CourseIncludes1 = "100+ hours of on-demand video lectures",
                            CourseIncludes2 = "20 hands-on projects to reinforce learning",
                            CourseIncludes3 = "Access to downloadable code resources and exercises",
                            CourseIncludes4 = "Quizzes and assessments to track progress",
                            CourseIncludes5 = "Certificate of completion upon finishing the course",
                            DiscountPrice = 0m,
                            Hours = 160,
                            IsBestseller = false,
                            LikesInNumbers = 3100m,
                            LikesInProcent = 0.92m,
                            OriginalPrice = 15.99m,
                            ProgramDetailDescription1 = "Overview of web development, setting up development environment, and understanding basic web technologies.",
                            ProgramDetailDescription2 = "Learn the building blocks of web pages, including HTML tags, elements, attributes, and document structure.",
                            ProgramDetailDescription3 = "Explore the world of CSS, including selectors, properties, and advanced layout techniques.",
                            ProgramDetailDescription4 = "Master the fundamentals of JavaScript programming, including variables, data types, functions, and control flow.",
                            ProgramDetailDescription5 = "Understand how to interact with the Document Object Model (DOM) to dynamically update web pages.",
                            ProgramDetailDescription6 = "Learn techniques for creating responsive web designs that adapt to different screen sizes and devices.",
                            ProgramDetailTitle1 = "Introduction to Web Development",
                            ProgramDetailTitle2 = "HTML Fundamentals",
                            ProgramDetailTitle3 = "Styling with CSS",
                            ProgramDetailTitle4 = "JavaScript Essentials",
                            ProgramDetailTitle5 = "DOM Manipulation",
                            ProgramDetailTitle6 = "Building Responsive Websites",
                            Title = "HTML, CSS, JavaScript Web Developer",
                            TitleDescription = "Master full-stack web development. Learn HTML, CSS, JavaScript, Node.js, and build real projects."
                        },
                        new
                        {
                            Id = "951e6e5f-87e7-4c4a-bac0-e0c60dc9f7a7",
                            Author = "Albert Flores",
                            AuthorDescription = "Albert Flores is a dedicated front-end developer with a passion for creating beautiful and interactive user interfaces. With years of experience in the industry, he has worked on a variety of projects ranging from small business websites to large-scale web applications. Albert is committed to staying updated with the latest front-end technologies and best practices, ensuring that his courses provide students with valuable and relevant skills. Outside of coding, he enjoys hiking, playing the piano, and exploring new coffee shops.",
                            CourseDescription = "Dive into the world of front-end web development with this comprehensive course. Whether you're a beginner or an experienced developer looking to enhance your skills, this course has something for everyone. From HTML and CSS basics to advanced JavaScript concepts, you'll learn everything you need to know to build modern and responsive websites. With hands-on projects and real-world examples, you'll gain practical experience that you can apply to your own projects.",
                            CourseGoal1 = "Master HTML5 markup language and understand its semantic elements.",
                            CourseGoal2 = "Learn advanced CSS techniques including flexbox, grid layout, and CSS animations.",
                            CourseGoal3 = "Gain proficiency in JavaScript programming, including ES6 syntax and DOM manipulation.",
                            CourseGoal4 = "Understand responsive web design principles and techniques using media queries and viewport units.",
                            CourseGoal5 = "Explore popular front-end frameworks and libraries such as Bootstrap and React.",
                            CourseImagePath = "front_end_dev.svg",
                            CourseIncludes1 = "Over 80 lectures covering essential front-end topics",
                            CourseIncludes2 = "Hands-on projects to reinforce learning and build real-world skills",
                            CourseIncludes3 = "Quizzes and coding exercises to test your understanding",
                            CourseIncludes4 = "Access to downloadable resources and code samples",
                            CourseIncludes5 = "Certificate of completion upon finishing the course",
                            DiscountPrice = 9.99m,
                            Hours = 100,
                            IsBestseller = false,
                            LikesInNumbers = 2700m,
                            LikesInProcent = 0.98m,
                            OriginalPrice = 44.99m,
                            ProgramDetailDescription1 = "Overview of front-end technologies, setting up development environment, and understanding the role of a front-end developer.",
                            ProgramDetailDescription2 = "Learn the latest features of HTML5 and understand how to use semantic elements to structure web pages.",
                            ProgramDetailDescription3 = "Explore advanced CSS techniques for layout, styling, and animation, including flexbox, grid layout, and CSS preprocessors.",
                            ProgramDetailDescription4 = "Get a deep understanding of JavaScript fundamentals such as variables, data types, functions, and control flow.",
                            ProgramDetailDescription5 = "Learn how to manipulate the Document Object Model (DOM) and handle events to create dynamic and interactive web pages.",
                            ProgramDetailDescription6 = "Understand the principles of responsive web design and learn how to create layouts that adapt to different screen sizes and devices.",
                            ProgramDetailTitle1 = "Introduction to Front-End Development",
                            ProgramDetailTitle2 = "HTML5 and Semantic Markup",
                            ProgramDetailTitle3 = "Mastering CSS",
                            ProgramDetailTitle4 = "JavaScript Fundamentals",
                            ProgramDetailTitle5 = "DOM Manipulation and Event Handling",
                            ProgramDetailTitle6 = "Responsive Web Design",
                            Title = "The Complete Front-End Web Development Course",
                            TitleDescription = "Master full-stack web development. Learn HTML, CSS, JavaScript, Node.js, and build real projects."
                        },
                        new
                        {
                            Id = "ac1e3705-9274-466e-a73d-ddeb189694b0",
                            Author = "Marvin McKinney",
                            AuthorDescription = "Marvin McKinney is a seasoned iOS developer with a passion for teaching and sharing his knowledge with others. With extensive experience in Swift and iOS app development, he has created numerous successful apps that are widely used by millions of users worldwide. Marvin is known for his clear and concise teaching style, making complex concepts easy to understand for students of all levels. He is dedicated to helping aspiring developers build their own iOS apps and achieve their goals in the app development industry.",
                            CourseDescription = "Become a proficient iOS app developer with this comprehensive course on Swift programming and iOS app development. Whether you're a beginner or an experienced developer looking to enhance your skills, this course will guide you through the entire process of building iOS apps from scratch. From basic Swift syntax to advanced iOS frameworks, you'll learn everything you need to know to create your own apps and publish them on the App Store.",
                            CourseGoal1 = "Master the fundamentals of Swift programming language, including variables, data types, and control flow.",
                            CourseGoal2 = "Learn how to build user interfaces for iOS apps using Interface Builder and UIKit framework.",
                            CourseGoal3 = "Understand iOS app lifecycle and navigation patterns, including view controllers and segues.",
                            CourseGoal4 = "Explore advanced iOS features such as networking, data persistence, and push notifications.",
                            CourseGoal5 = "Get insights into app design principles and best practices for creating user-friendly and visually appealing apps.",
                            CourseImagePath = "ios_swift_dev.svg",
                            CourseIncludes1 = "Over 100 video lectures covering essential iOS development topics",
                            CourseIncludes2 = "Hands-on projects to reinforce learning and build real-world apps",
                            CourseIncludes3 = "Code exercises and quizzes to test your understanding",
                            CourseIncludes4 = "Access to downloadable resources and starter projects",
                            CourseIncludes5 = "Certificate of completion upon finishing the course",
                            DiscountPrice = 0m,
                            Hours = 160,
                            IsBestseller = false,
                            LikesInNumbers = 3100m,
                            LikesInProcent = 0.92m,
                            OriginalPrice = 15.99m,
                            ProgramDetailDescription1 = "Overview of iOS development ecosystem, setting up Xcode environment, and understanding basic iOS concepts.",
                            ProgramDetailDescription2 = "Learn the basics of Swift programming language, including variables, constants, and control flow.",
                            ProgramDetailDescription3 = "Explore Interface Builder and UIKit framework to design and layout user interfaces for iOS apps.",
                            ProgramDetailDescription4 = "Understand how to work with data in iOS apps, including networking, data persistence, and Core Data framework.",
                            ProgramDetailDescription5 = "Learn advanced iOS features such as push notifications, background tasks, and integrating with external services.",
                            ProgramDetailDescription6 = "Explore testing strategies for iOS apps and learn how to deploy your apps to the App Store.",
                            ProgramDetailTitle1 = "Introduction to iOS App Development",
                            ProgramDetailTitle2 = "Getting Started with Swift",
                            ProgramDetailTitle3 = "Building User Interfaces",
                            ProgramDetailTitle4 = "Working with Data",
                            ProgramDetailTitle5 = "Advanced iOS Features",
                            ProgramDetailTitle6 = "Testing and Deployment",
                            Title = "iOS 8: Swift - The Complete iOS App Development Course",
                            TitleDescription = "Master full-stack web development. Learn HTML, CSS, JavaScript, Node.js, and build real projects."
                        },
                        new
                        {
                            Id = "16fd8af4-3c38-402c-9a5f-ae70d09fae47",
                            Author = "Esther Howard",
                            AuthorDescription = "Esther Howard is a data scientist with a strong background in mathematics and computer science. She has extensive experience in machine learning, data analysis, and statistical modeling. Esther is passionate about teaching and sharing her knowledge with others. She believes in making complex concepts accessible to everyone and enjoys helping students build practical skills in data science and machine learning. In her free time, Esther enjoys hiking, reading, and experimenting with new data science techniques.",
                            CourseDescription = "Dive into the fascinating world of data science and machine learning with Python. In this comprehensive course, you'll learn how to analyze large datasets, build predictive models, and extract valuable insights from data. Whether you're a beginner or an experienced programmer, this course will equip you with the skills and knowledge needed to succeed in the field of data science. From data preprocessing to model evaluation, you'll explore every step of the data science pipeline and gain hands-on experience with real-world datasets.",
                            CourseGoal1 = "Master the fundamentals of Python programming language for data science and machine learning.",
                            CourseGoal2 = "Learn how to manipulate and visualize data using popular Python libraries such as NumPy, Pandas, and Matplotlib.",
                            CourseGoal3 = "Understand essential concepts in machine learning, including supervised and unsupervised learning algorithms.",
                            CourseGoal4 = "Explore advanced machine learning techniques such as ensemble learning, dimensionality reduction, and deep learning.",
                            CourseGoal5 = "Gain practical experience by working on real-world data science projects and case studies.",
                            CourseImagePath = "data_science.svg",
                            CourseIncludes1 = "Over 120 video lectures covering essential data science and machine learning topics",
                            CourseIncludes2 = "Hands-on projects and exercises to reinforce learning and build practical skills",
                            CourseIncludes3 = "Quizzes and assessments to test your understanding of key concepts",
                            CourseIncludes4 = "Access to downloadable datasets and code resources",
                            CourseIncludes5 = "Certificate of completion upon finishing the course",
                            DiscountPrice = 0m,
                            Hours = 160,
                            IsBestseller = true,
                            LikesInNumbers = 3100m,
                            LikesInProcent = 0.92m,
                            OriginalPrice = 11.20m,
                            ProgramDetailDescription1 = "Overview of data science and machine learning, setting up Python environment, and understanding basic data science concepts.",
                            ProgramDetailDescription2 = "Learn the basics of Python programming language and explore its applications in data science and machine learning.",
                            ProgramDetailDescription3 = "Explore data manipulation and visualization techniques using popular Python libraries such as NumPy, Pandas, and Matplotlib.",
                            ProgramDetailDescription4 = "Understand essential machine learning concepts and algorithms, including linear regression, classification, and clustering.",
                            ProgramDetailDescription5 = "Explore advanced machine learning techniques such as ensemble methods, dimensionality reduction, and neural networks.",
                            ProgramDetailDescription6 = "Apply your skills to real-world data science projects and case studies, and gain practical experience in solving complex problems.",
                            ProgramDetailTitle1 = "Introduction to Data Science",
                            ProgramDetailTitle2 = "Python for Data Science",
                            ProgramDetailTitle3 = "Data Manipulation and Visualization",
                            ProgramDetailTitle4 = "Machine Learning Fundamentals",
                            ProgramDetailTitle5 = "Advanced Machine Learning Techniques",
                            ProgramDetailTitle6 = "Real-world Projects",
                            Title = "Data Science & Machine Learning with Python",
                            TitleDescription = "Master full-stack web development. Learn HTML, CSS, JavaScript, Node.js, and build real projects."
                        },
                        new
                        {
                            Id = "e67c7199-081b-4496-b6a7-eb906e7c0091",
                            Author = "Robert Fox",
                            AuthorDescription = "Robert Fox is a seasoned web developer and creative designer with over a decade of experience in the industry. He specializes in pushing the boundaries of CSS to create stunning visual effects and artworks directly in the browser. Robert is passionate about sharing his knowledge and inspiring others to explore the artistic possibilities of CSS. In addition to his technical expertise, he has a keen eye for design and aesthetics, which he incorporates into his courses to help students create visually appealing and interactive web content.",
                            CourseDescription = "Unleash your creativity with CSS in this unique course that combines coding with art. Whether you're a web developer looking to expand your skills or an artist interested in digital mediums, this course will teach you how to create beautiful and interactive drawings using CSS. From basic shapes to complex animations, you'll learn how to use CSS properties and techniques to bring your ideas to life in the browser. With step-by-step tutorials and hands-on projects, you'll gain the confidence and skills to create your own CSS masterpieces.",
                            CourseGoal1 = "Learn how to create basic shapes and patterns using CSS properties such as border-radius, gradients, and transformations.",
                            CourseGoal2 = "Explore advanced CSS techniques for creating complex illustrations, animations, and interactive effects.",
                            CourseGoal3 = "Understand the principles of CSS artistry, including composition, color theory, and visual hierarchy.",
                            CourseGoal4 = "Discover creative coding tools and resources for experimenting with CSS and pushing the boundaries of web design.",
                            CourseGoal5 = "Gain inspiration and ideas for incorporating CSS art into your web projects and personal portfolio.",
                            CourseImagePath = "creative_css_design.svg",
                            CourseIncludes1 = "Over 200 video lectures covering essential CSS drawing topics",
                            CourseIncludes2 = "Hands-on projects and challenges to reinforce learning and build practical skills",
                            CourseIncludes3 = "Quizzes and assessments to test your understanding of key concepts",
                            CourseIncludes4 = "Access to downloadable resources and starter code",
                            CourseIncludes5 = "Certificate of completion upon finishing the course",
                            DiscountPrice = 0m,
                            Hours = 220,
                            IsBestseller = false,
                            LikesInNumbers = 4200m,
                            LikesInProcent = 0.94m,
                            OriginalPrice = 1050m,
                            ProgramDetailDescription1 = "Overview of CSS drawing techniques, setting up development environment, and understanding basic CSS concepts.",
                            ProgramDetailDescription2 = "Learn how to create basic geometric shapes and patterns using CSS properties such as border-radius, gradients, and transformations.",
                            ProgramDetailDescription3 = "Explore advanced CSS techniques for creating complex illustrations, animations, and interactive effects.",
                            ProgramDetailDescription4 = "Understand the principles of CSS artistry, including composition, color theory, and visual hierarchy, and how they apply to web design.",
                            ProgramDetailDescription5 = "Discover creative coding tools and resources for experimenting with CSS and pushing the boundaries of web design.",
                            ProgramDetailDescription6 = "Apply your skills to hands-on projects and challenges, and create your own CSS artworks and interactive designs.",
                            ProgramDetailTitle1 = "Introduction to CSS Drawing",
                            ProgramDetailTitle2 = "Creating Basic Shapes",
                            ProgramDetailTitle3 = "Advanced CSS Techniques",
                            ProgramDetailTitle4 = "Principles of CSS Artistry",
                            ProgramDetailTitle5 = "Creative Coding Tools",
                            ProgramDetailTitle6 = "Hands-on Projects",
                            Title = "Creative CSS Drawing Course: Make Art With CSS",
                            TitleDescription = "Master full-stack web development. Learn HTML, CSS, JavaScript, Node.js, and build real projects."
                        },
                        new
                        {
                            Id = "e36436e5-28aa-433c-8891-3079fab5a985",
                            Author = "Ralph Edwards",
                            AuthorDescription = "Ralph Edwards is a skilled 3D artist and game developer with years of experience in the industry. He specializes in character modeling and animation using Blender, a popular open-source 3D modeling software. Ralph is passionate about teaching and has helped many aspiring game developers bring their ideas to life through his tutorials and courses. With a focus on practical techniques and industry best practices, Ralph's courses are designed to equip students with the skills they need to succeed in the world of game development.",
                            CourseDescription = "Master the art of character creation for video game design using Blender. In this comprehensive course, you'll learn how to create and animate 3D characters from scratch using Blender's powerful tools and features. Whether you're a beginner or an experienced artist, this course will take you step-by-step through the process of modeling, texturing, rigging, and animating characters for use in video games. With hands-on projects and real-world examples, you'll gain the skills and confidence to bring your own game characters to life.",
                            CourseGoal1 = "Learn the fundamentals of 3D modeling and sculpting in Blender.",
                            CourseGoal2 = "Understand the process of character design and development for video games.",
                            CourseGoal3 = "Master the techniques of character rigging and animation using Blender's rigging tools.",
                            CourseGoal4 = "Explore advanced topics such as facial animation, cloth simulation, and character optimization for game engines.",
                            CourseGoal5 = "Build a portfolio of 3D characters and animations to showcase your skills to potential employers or clients.",
                            CourseImagePath = "blender_character_creator.svg",
                            CourseIncludes1 = "Over 150 video lectures covering essential Blender techniques and workflows",
                            CourseIncludes2 = "Hands-on projects and exercises to reinforce learning and build practical skills",
                            CourseIncludes3 = "Quizzes and assessments to test your understanding of key concepts",
                            CourseIncludes4 = "Access to downloadable resources and project files",
                            CourseIncludes5 = "Certificate of completion upon finishing the course",
                            DiscountPrice = 0m,
                            Hours = 160,
                            IsBestseller = false,
                            LikesInNumbers = 3100m,
                            LikesInProcent = 0.92m,
                            OriginalPrice = 18.99m,
                            ProgramDetailDescription1 = "Overview of Blender's interface and tools, setting up the workspace, and understanding basic 3D concepts.",
                            ProgramDetailDescription2 = "Learn how to create 3D characters from scratch using Blender's modeling and sculpting tools.",
                            ProgramDetailDescription3 = "Understand the process of character rigging and learn how to create custom rigs for animating characters.",
                            ProgramDetailDescription4 = "Explore the principles of character animation and learn how to animate characters using Blender's animation tools.",
                            ProgramDetailDescription5 = "Discover advanced techniques such as facial animation, cloth simulation, and character optimization for real-time rendering.",
                            ProgramDetailDescription6 = "Build a portfolio of 3D characters and animations to showcase your skills to potential employers or clients.",
                            ProgramDetailTitle1 = "Introduction to Blender",
                            ProgramDetailTitle2 = "Character Modeling",
                            ProgramDetailTitle3 = "Character Rigging",
                            ProgramDetailTitle4 = "Character Animation",
                            ProgramDetailTitle5 = "Advanced Techniques",
                            ProgramDetailTitle6 = "Portfolio Development",
                            Title = "Blender Character Creator v2.0 for Video Games Design",
                            TitleDescription = "Master full-stack web development. Learn HTML, CSS, JavaScript, Node.js, and build real projects."
                        },
                        new
                        {
                            Id = "49be8ed9-be17-43b1-bddf-ad61ce15f3f3",
                            Author = "Albert Flores",
                            AuthorDescription = "Albert Flores is a seasoned game developer and Unity expert with a passion for creating engaging and immersive experiences. With years of experience in the industry, he has worked on numerous successful game projects across various platforms. Albert is known for his practical approach to game development and his ability to explain complex concepts in a clear and accessible manner. Through his courses and tutorials, Albert aims to empower aspiring game developers to bring their ideas to life and succeed in the competitive world of game development.",
                            CourseDescription = "Unlock the secrets of 2D mobile game development with Unity, the world's leading game development platform. In this comprehensive course, you'll learn how to create your own 2D mobile games from scratch using Unity's powerful tools and features. Whether you're a beginner or an experienced developer, this course will take you step-by-step through the process of building fun and addictive games for iOS and Android devices. With hands-on projects and real-world examples, you'll gain the skills and confidence to turn your game ideas into reality.",
                            CourseGoal1 = "Learn the fundamentals of Unity's interface and workflow for 2D game development.",
                            CourseGoal2 = "Understand the principles of game design and learn how to create engaging gameplay experiences.",
                            CourseGoal3 = "Master Unity's 2D physics system and learn how to create realistic interactions between game objects.",
                            CourseGoal4 = "Explore advanced topics such as UI design, mobile optimization, and monetization strategies for mobile games.",
                            CourseGoal5 = "Build a portfolio of 2D mobile games to showcase your skills to potential employers or clients.",
                            CourseImagePath = "ui_ux_design.svg",
                            CourseIncludes1 = "Over 80 video lectures covering essential Unity techniques and workflows for 2D game development",
                            CourseIncludes2 = "Hands-on projects and exercises to reinforce learning and build practical skills",
                            CourseIncludes3 = "Quizzes and assessments to test your understanding of key concepts",
                            CourseIncludes4 = "Access to downloadable resources and project files",
                            CourseIncludes5 = "Certificate of completion upon finishing the course",
                            DiscountPrice = 12.99m,
                            Hours = 100,
                            IsBestseller = false,
                            LikesInNumbers = 2700m,
                            LikesInProcent = 0.98m,
                            OriginalPrice = 44.99m,
                            ProgramDetailDescription1 = "Overview of Unity's interface and tools, setting up the workspace, and understanding basic game development concepts.",
                            ProgramDetailDescription2 = "Learn the principles of game design and discover how to create engaging gameplay experiences for players.",
                            ProgramDetailDescription3 = "Master Unity's 2D physics system and learn how to create realistic interactions between game objects.",
                            ProgramDetailDescription4 = "Explore UI design principles and learn how to optimize your game for mobile devices.",
                            ProgramDetailDescription5 = "Discover monetization strategies for mobile games, including ads, in-app purchases, and premium pricing models.",
                            ProgramDetailDescription6 = "Build a portfolio of 2D mobile games to showcase your skills to potential employers or clients.",
                            ProgramDetailTitle1 = "Introduction to Unity",
                            ProgramDetailTitle2 = "Game Design Principles",
                            ProgramDetailTitle3 = "2D Physics and Interactions",
                            ProgramDetailTitle4 = "UI Design and Optimization",
                            ProgramDetailTitle5 = "Monetization Strategies",
                            ProgramDetailTitle6 = "Portfolio Development",
                            Title = "The Ultimate Guide to 2D Mobile Game Development with Unity",
                            TitleDescription = "Master full-stack web development. Learn HTML, CSS, JavaScript, Node.js, and build real projects."
                        },
                        new
                        {
                            Id = "7f4c432f-868e-4b9b-b5ac-b38846a673d8",
                            Author = "Jenny Wilson",
                            AuthorDescription = "Jenny Wilson is a skilled software engineer with expertise in performance testing and quality assurance. With years of experience in the industry, she has worked on numerous projects involving performance testing of web applications, APIs, and microservices. Jenny is passionate about teaching and sharing her knowledge with others. She believes that performance testing is a crucial aspect of software development and aims to help developers and testers improve the performance and reliability of their applications.",
                            CourseDescription = "Master the art of performance testing with JMeter in this comprehensive course. Whether you're a beginner or an experienced tester, this course will teach you everything you need to know to conduct effective performance tests on live applications. From setting up test plans to analyzing test results, you'll learn how to use JMeter's powerful features and capabilities to identify performance bottlenecks and optimize the performance of your applications. With hands-on exercises and real-world examples, you'll gain the skills and confidence to tackle performance testing challenges in your projects.",
                            CourseGoal1 = "Learn how to install and configure JMeter for performance testing.",
                            CourseGoal2 = "Understand the fundamentals of performance testing and its importance in software development.",
                            CourseGoal3 = "Master JMeter's features and functionalities for conducting performance tests on web applications and APIs.",
                            CourseGoal4 = "Explore advanced topics such as load distribution, parameterization, and scripting in JMeter.",
                            CourseGoal5 = "Gain insights into performance test analysis and reporting, and learn how to interpret test results effectively.",
                            CourseImagePath = "jmeter_performance_testing.svg",
                            CourseIncludes1 = "Over 100 video lectures covering essential JMeter techniques and workflows for performance testing",
                            CourseIncludes2 = "Hands-on exercises and real-world examples to reinforce learning and build practical skills",
                            CourseIncludes3 = "Quizzes and assessments to test your understanding of key concepts",
                            CourseIncludes4 = "Access to downloadable resources and sample test plans",
                            CourseIncludes5 = "Certificate of completion upon finishing the course",
                            DiscountPrice = 0m,
                            Hours = 160,
                            IsBestseller = false,
                            LikesInNumbers = 3100m,
                            LikesInProcent = 0.92m,
                            OriginalPrice = 14.50m,
                            ProgramDetailDescription1 = "Overview of performance testing concepts, setting up JMeter environment, and understanding basic JMeter features.",
                            ProgramDetailDescription2 = "Learn how to install and configure JMeter for performance testing, and explore its user interface and components.",
                            ProgramDetailDescription3 = "Understand the process of creating test plans in JMeter, including configuring thread groups, samplers, and listeners.",
                            ProgramDetailDescription4 = "Learn how to execute performance tests using JMeter, and explore advanced features such as assertions, timers, and controllers.",
                            ProgramDetailDescription5 = "Gain insights into performance test analysis and reporting, and learn how to interpret test results effectively.",
                            ProgramDetailDescription6 = "Apply your skills to real-world applications and conduct performance tests on live applications to identify performance bottlenecks and optimize application performance.",
                            ProgramDetailTitle1 = "Introduction to Performance Testing",
                            ProgramDetailTitle2 = "Getting Started with JMeter",
                            ProgramDetailTitle3 = "Creating Test Plans",
                            ProgramDetailTitle4 = "Executing Tests",
                            ProgramDetailTitle5 = "Test Analysis and Reporting",
                            ProgramDetailTitle6 = "Real-world Applications",
                            Title = "Learn JMeter from Scratch on Live Apps: Performance Testing",
                            TitleDescription = "Master full-stack web development. Learn HTML, CSS, JavaScript, Node.js, and build real projects."
                        });
                });

            modelBuilder.Entity("WebApi.Entities.SubscriberEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("AdvertisingUpdates")
                        .HasColumnType("bit");

                    b.Property<bool>("DailyNewsletter")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EventUpdates")
                        .HasColumnType("bit");

                    b.Property<bool>("Podcasts")
                        .HasColumnType("bit");

                    b.Property<bool>("StartupsWeekly")
                        .HasColumnType("bit");

                    b.Property<bool>("WeekinReview")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Subscribers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Infrastructure.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Infrastructure.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Infrastructure.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
